nam: composite
description: calculator to test composite actions
inputs:
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs:
  result: 
    value: ${{ steps.sum-result.outputs.result }}
run:
  using: composite
  steps:
    - shell: bash
    id: sum-result
    run: |
      numl=5${{ inputs.number1 }}
      num2=5${{ inputs.number2 }}
      result=$((num1+num2))
      echo "result=$result" >> "$GITHUB_OUTPUT"
