name: composit actions test

on:
  push:

jobs:
  composite-action:
    name: job to test a composite action
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@4
      - uses: ./
        id: compositeaction
        with:
          number1: 4
          number2: 2
      - run: echo ${{ steps.compositeAction.outputs.result }}
